# Это название твоего приложения. Как папка на компьютере, только официально.
name: bmi_calculator

# Короткое описание: что эта штука вообще делает. 
description: A new Flutter application.

# Версия приложения. 
# 1.0.0 — то, что видят пользователи. 
# +1 — технический номер сборки (нужен для App Store и Google Play).
version: 1.0.0+1

# Здесь мы говорим: "Мой код работает только на этих версиях Dart".
# Это как системные требования у компьютерной игры.
environment:
  sdk: ">=2.12.0 <4.0.0"

# РАЗДЕЛ "ЗАВИСИМОСТИ": Это инструменты, которые ты берешь "в аренду", 
# чтобы не писать весь код с нуля.
dependencies:
  # Сам движок Flutter. Без него ничего не заработает.
  flutter:
    sdk: flutter

  # Набор стандартных иконок в стиле Apple (iOS).
  cupertino_icons: ^1.0.9
  
  # Огромная библиотека крутых иконок (бренды, соцсети и т.д.).
  font_awesome_flutter: ^10.1.0

# РАЗДЕЛ "ДЛЯ РАЗРАБОТЧИКА": Эти штуки нужны тебе, пока ты пишешь код,
# но обычному пользователю в телефон они не попадут.
dev_dependencies:
  # Инструменты для проведения тестов (проверка кода на ошибки).
  flutter_test:
    sdk: flutter
  
  # "Полиция кода" — подсказывает, как писать красиво и по правилам.
  flutter_lints: ^3.0.0

# СПЕЦИФИКАЦИИ FLUTTER: Личные настройки движка.
flutter:
  # Включаем поддержку Material Design (стиль кнопок и меню от Google).
  # Если тут поставить false, приложение будет выглядеть как голый скелет.
  uses-material-design: true